on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Title'
        type: string 
        required: true
      body:
        description: 'body'
        type: string
        required: false

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno run --allow-write script/new_post.ts --tile=$TITLE --body=$BODY
        env:
          TITLE: ${{ inputs.title }}
          BODY: ${{ inputs.body }}